---
- name: Create base directory
  ansible.builtin.file:
    path: "{{ docker_stacks_path }}"
    state: directory
    owner: "{{ username }}"
    mode: "0775"
  become: true

- name: Create volumes
  community.docker.docker_volume:
    name: "{{ item.name }}"
  with_items: "{{ docker_volumes }}"

- name: Create networks
  community.general.docker_network:
    name: "{{ item.name }}"
    attachable: true
    ipam_config:
      - subnet: "{{ item.subnet }}"
  with_items: "{{ docker_networks }}"

- name: Setup services properties
  ansible.builtin.set_fact:
    services: "{{ [docker_stack_services, docker_stack_services_custom]|
           community.general.lists_mergeby('name',
                                           recursive=true) }}"

- name: Setup services by state
  ansible.builtin.set_fact:
    enabled_services: "{{  services | selectattr('enabled', 'true') | list }}"
    disabled_services: "{{  services | selectattr('enabled', 'false') | list }}"




- name: Setup enabled Services
  ansible.builtin.include_tasks: setup_service.yaml
  loop: "{{ enabled_services }}"
  loop_control:
    loop_var: outer_item

- name: Clean disabled services
  ansible.builtin.include_tasks: remove_service.yaml
  loop: "{{ disabled_services }}"
  loop_control:
    loop_var: outer_item
