---
- name: remove_service | Remove Service {{ outer_item.name }}
  become: true
  block:
    - name: remove_service | Synchronize {{ outer_item.name }} directories
      ansible.posix.synchronize:
        src: "services/{{ outer_item.name }}"
        dest: "{{ docker_stacks_services_path }}"
        delete: false
        recursive: true
        perms: false
        rsync_opts:
          - "--no-motd"
          - "--exclude=.env"
      become_user: "{{ username }}"
    - name: remove_service | Disable Ports {{ outer_item.name }}
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      with_items: "{{ outer_item.ports }}"
    - name: remove_service | Disable service {{ outer_item.name }}
      community.docker.docker_compose_v2:
        state: absent
        remove_orphans: true
        project_src: "{{ docker_stacks_services_path }}/{{ outer_item.name }}"
