---
- name: setup_service | Deploy Service {{ outer_item.name }}
  become: true
  block:
    - name: setup_service | Synchronize {{ outer_item.name }} directories
      ansible.posix.synchronize:
        src: "services/{{ outer_item.name }}"
        dest: "{{ docker_stacks_services_path }}"
        delete: false
        recursive: true
        perms: false
        rsync_opts:
          - "--no-motd"
          - "--exclude=.env"
    - name: setup_service | Setup Ports {{ outer_item.name }}
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      with_items: "{{ outer_item.ports }}"
    - name: setup_service | Create service directories for {{ outer_item.name }}
      ansible.builtin.file:
        path: "{{ docker_configs.data_path }}{{ item.path }}"
        state: directory
        owner: "{{ (item.owner is defined and item.owner != '') | ternary(item.owner, username) }}"
        mode: "0775"
      with_items: "{{ outer_item.directories }}"
    - name: setup_service | Setup service {{ outer_item.name }}
      community.docker.docker_compose_v2:
        state: present
        build: policy
        project_src: "{{ docker_stacks_services_path }}/{{ outer_item.name }}"
        check_mode: "{{ docker_compose_check_mode }}"
  when: outer_item.enabled is true
