---
version: '3.7'

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DATA_PATH}/volumes/wireguard/wireguard/config:/config
    ports:
      - "5000:5000"
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - .env
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # use the network of the 'wireguard' service. this enables to show active clients in the status page
    network_mode: service:wireguard
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ${DATA_PATH}/volumes/wireguard/wireguard-ui/db:/app/db
      - ${DATA_PATH}/volumes/wireguard/wireguard/config:/etc/wireguard
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    env_file:
      - .env
