---

networks:
  proxy_network:
    name: proxy_network
    external: true
  nextcloud:
services:
  nextcloud_db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}/volumes/nextcloud/postgres:/var/lib/postgresql/data
    networks:
      - nextcloud
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  nextcloud_postgres_backups:
    image: prodrigestivill/postgres-backup-local:16
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
      - ${DATA_PATH}/docker-backups/databases:/backups
    links:
      - nextcloud_db
    networks:
      - nextcloud
    environment:
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    env_file:
      - .env
  nextcloud:
    image: nextcloud:28.0.4
    restart: always
    volumes:
      - ${DATA_PATH}/volumes/nextcloud/nextcloud:/var/www/html
      - ${MEDIA_PATH}/nextcloud-data:/var/www/html/data
    networks:
      - nextcloud
      - proxy_network
    environment:
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
    depends_on:
      - nextcloud_db
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.entrypoints=${DEFAULT_ENDPOINT}
      - traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nextcloud.tls=${ENABLE_SSL}
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud.middlewares=nextcloud_redirectregex
      - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true
      - traefik.http.routers.nextcloud.tls.certresolver=letsencryptresolver
      - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex="https://(.*)/.well-known/(?:card|cal)dav"
      - traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement="https://$${1}/remote.php/dav"
      - traefik.docker.network=proxy_network
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - .env
