---
version: "3.7"

networks:
  proxy_network:
    name: proxy_network
    external: true
  torrents_network:
    external: true
services:
  # Web Reverse Proxy
  traefik:
    image: traefik:v2.8
    restart: always
    container_name: traefik
    domainname: ${TRAEFIK_DOMAIN}
    env_file:
      - .env
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ${DATA_PATH}/volumes/traefik/certs:/etc/certs/
      - ${DATA_PATH}/volumes/traefik/letsencrypt:/letsencrypt
      - ${DATA_PATH}/volumes/traefik/logs:/var/log
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.priority=1
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - com.centurylinklabs.watchtower.enable=true
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=web,websecure
      - traefik.http.routers.traefik.tls.certresolver=letsencryptresolver
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=strip
      - traefik.http.middlewares.strip.stripprefix.prefixes=/traefik
    command:
      - --certificatesresolvers.letsencryptresolver.acme.email=${TRAEFIK_MAIL}
      - --certificatesresolvers.letsencryptresolver.acme.dnschallenge.provider=${TRAEFIK_DNS_PROVIDER}
      - --certificatesresolvers.letsencryptresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencryptresolver
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN_WILDCARD}
      - --entrypoints.websecure.http.tls.domains[0].sans=${DOMAIN_WILDCARD_SANS}
    networks:
      - proxy_network
      - torrents_network
    dns:
      - ${TRAEFIK_DNS1}
      - ${TRAEFIK_DNS2}
    extra_hosts:
      - host.docker.internal:172.17.0.1
