---
- name: Check if resolv.conf have the correct dns
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ resolvconf_nameservers | first}}"
    state: present
  check_mode: yes
  register: resolv_configured
  failed_when: resolv_configured is changed

- name: Configure systemd-resolved for PiHole
  become: true
  block:
    - name: Disable stub resolver in systemd-resolved config
      community.general.ini_file:
        path: /etc/systemd/resolved.conf
        section: Resolve
        option: DNSStubListener
        value: "no"
        mode: "0644"
        backup: true

    - name: Remove /etc/resolv.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent

    - name: Create link /etc/resolv.conf
      ansible.builtin.template:
        src: resolved.j2
        dest: /etc/resolv.conf
        mode: "0644"
      notify:
        - Restart Resolved server
  when: resolv_configured is changed
