---
version: '3'

volumes:
  dojo_pihole_data:
    external: true
  dojo_pihole_dns_data:
    external: true
  dojo_homeassistant_data:
    external: true
  dojo_homeassistant_database:
    external: true
  dojo_influxdb_data:
    external: true
  dojo_freshrss_data:
    external: true
  dojo_freshrss_database:
    external: true
networks:
  monitoring_network:
    external: true
  pihole_network:
  homeassistant:
  freshrss:
  proxy_network:
    external: true
services:
  pihole:
    image: pihole/pihole:nightly
    container_name: pihole
    domainname: pihole
    restart: unless-stopped
    networks:
      - pihole_network
      - proxy_network
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:67:67/udp'
    expose:
      - 80
    volumes:
      - ./config/pihole/custom.list:/etc/pihole/custom.list
      - dojo_pihole_data:/etc/pihole/
      - dojo_pihole_dns_data:/etc/dnsmasq.d/
    environment:
      - ServerIP=${PIHOLE_IP}
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${PIHOLE_PASS}
      - VIRTUAL_HOST=${PIHOLE_DOMAIN}
      - DNS1=${PIHOLE_DNS1}
      - DNS2=${PIHOLE_DNS2}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pihole.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.pihole.rule=Host(`${PIHOLE_DOMAIN}`)'
      - 'traefik.http.routers.pihole.tls=${ENABLE_SSL}'
      - 'traefik.http.routers.pihole.tls.certresolver=letsencryptresolver'
      - 'traefik.docker.network=proxy_network'
      - 'traefik.http.services.pihole.loadbalancer.server.port=${PIHOLE_PORT}'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'docker-volume-backup.stop-during-backup=true'
    dns:
      - 127.0.0.1
      - ${PIHOLE_DNS1}
      - ${PIHOLE_DNS2}
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    restart: unless-stopped
    networks:
      - monitoring_network
      - pihole_network
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD=${PIHOLE_PASS}
    expose:
      - 9617
    ports:
      - 9617:9617

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    volumes:
      - ./config/homeassistant/blueprints:/config/blueprints
      - ./config/homeassistant/automations.yaml:/config/automations.yaml
      - ./config/homeassistant/configuration.yaml:/config/configuration.yaml
      - ./config/homeassistant/scenes.yaml:/config/scenes.yaml
      - ./config/homeassistant/scripts.yaml:/config/scripts.yaml
      - ./config/homeassistant/secrets.yaml:/config/secrets.yaml
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    depends_on:
      - homeassistant_postgres
      - homeassistant_influxdb
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'docker-volume-backup.stop-during-backup=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.homeassistant.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.homeassistant.rule=Host(`${HOMEASSISTANT_DOMAIN}`)'
      - 'traefik.http.routers.homeassistant.tls=${ENABLE_SSL}'
      - 'traefik.http.routers.homeassistant.tls.certresolver=letsencryptresolver'
      - 'traefik.http.services.homeassistant.loadbalancer.server.port=8123'

  webirc:
    image: thelounge/thelounge:latest
    container_name: webirc
    domainname: webirc
    restart: unless-stopped
    networks:
      - proxy_network
    ports:
      - 113:9001
      - 9000:9000
    volumes:
      - ${CONFIG_PATH}/irc:/var/opt/thelounge
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.irc.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.irc.rule=Host(`${IRC_DOMAIN}`)'
      - 'traefik.http.routers.irc.tls==${ENABLE_SSL}'
      - 'traefik.http.routers.irc.tls.certresolver=letsencryptresolver'
      - 'traefik.docker.network=proxy_network'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'docker-volume-backup.stop-during-backup=true'

  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    domainname: freshrss
    restart: unless-stopped
    networks:
      - proxy_network
      - freshrss
    volumes:
      - dojo_freshrss_data:/var/opt/thelounge
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.freshrss.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.freshrss.rule=Host(`${FRESHRSS_DOMAIN}`)'
      - 'traefik.http.routers.freshrss.tls==${ENABLE_SSL}'
      - 'traefik.http.routers.freshrss.tls.certresolver=letsencryptresolver'
      - 'traefik.http.routers.freshrss.middlewares=freshrssM1,freshrssM2'
      - 'traefik.http.middlewares.freshrssM1.compress=true'
      - 'traefik.http.middlewares.freshrssM2.headers.browserXssFilter=true'
      - 'traefik.http.middlewares.freshrssM2.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.freshrssM2.headers.frameDeny=true'
      - 'traefik.http.middlewares.freshrssM2.headers.referrerPolicy=no-referrer-when-downgrade'
      - 'traefik.http.middlewares.freshrssM2.headers.stsSeconds=31536000'
      - 'traefik.docker.network=proxy_network'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'docker-volume-backup.stop-during-backup=true'
    environment:
      TZ: Europe/Lisbon
      CRON_MIN: '3,33'
  fressrss_database:
    image: postgres:14
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    networks:
      - freshrss
    volumes:
      - dojo_freshrss_database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${FRESHRSS_DATABASE_DB}
      POSTGRES_USER: ${FRESHRSS_DATABASE_USER}
      POSTGRES_PASSWORD: ${FRESHRSS_DATABASE_PASSWORD}
