---
version: '3'

volumes:
  dojo_pihole_data:
    external: true
  dojo_pihole_dns_data:
    external: true
  dojo_homeassistant_data:
    external: true
  dojo_homeassistant_database:
    external: true
  dojo_influxdb_data:
    external: true
networks:
  monitoring_network:
    external: true
  pihole_network:
  homeassistant:
  freshrss:
  proxy_network:
    external: true
services:
  pihole:
    image: pihole/pihole:nightly
    container_name: pihole
    domainname: pihole
    restart: unless-stopped
    networks:
      - pihole_network
      - proxy_network
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:67:67/udp'
    expose:
      - 80
    volumes:
      - ./config/pihole/custom.list:/etc/pihole/custom.list
      - dojo_pihole_data:/etc/pihole/
      - dojo_pihole_dns_data:/etc/dnsmasq.d/
    environment:
      - ServerIP=${PIHOLE_IP}
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${PIHOLE_PASS}
      - VIRTUAL_HOST=${PIHOLE_DOMAIN}
      - DNS1=${PIHOLE_DNS1}
      - DNS2=${PIHOLE_DNS2}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pihole.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.pihole.rule=Host(`${PIHOLE_DOMAIN}`)'
      - 'traefik.http.routers.pihole.tls=${ENABLE_SSL}'
      - 'traefik.http.routers.pihole.tls.certresolver=letsencryptresolver'
      - 'traefik.docker.network=proxy_network'
      - 'traefik.http.services.pihole.loadbalancer.server.port=${PIHOLE_PORT}'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'docker-volume-backup.stop-during-backup=true'
    dns:
      - 127.0.0.1
      - ${PIHOLE_DNS1}
      - ${PIHOLE_DNS2}
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    restart: unless-stopped
    networks:
      - monitoring_network
      - pihole_network
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD=${PIHOLE_PASS}
    expose:
      - 9617
    ports:
      - 9617:9617

  webirc:
    image: thelounge/thelounge:latest
    container_name: webirc
    domainname: webirc
    restart: unless-stopped
    networks:
      - proxy_network
    ports:
      - 113:9001
      - 9000:9000
    volumes:
      - ${CONFIG_PATH}/irc:/var/opt/thelounge
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.irc.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.irc.rule=Host(`${IRC_DOMAIN}`)'
      - 'traefik.http.routers.irc.tls==${ENABLE_SSL}'
      - 'traefik.http.routers.irc.tls.certresolver=letsencryptresolver'
      - 'traefik.docker.network=proxy_network'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'docker-volume-backup.stop-during-backup=true'

  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - ${CONFIG_PATH}/emby:/config # Configuration directory
      - /mnt/shared-data:/mnt/share # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: on-failure
    networks:
      - proxy_network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.emby.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.emby.rule=Host(`${EMBY_DOMAIN}`)'
      - 'traefik.http.routers.emby.tls=${ENABLE_SSL}'
      - 'traefik.http.routers.emby.tls.certresolver=letsencryptresolver'
      - 'traefik.docker.network=proxy_network'
      - 'traefik.http.services.emby.loadbalancer.server.port=8096'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'docker-volume-backup.stop-during-backup=true'

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - proxy_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - /mnt/shared-data:/downloads
    ports:
      - 8010:8080
      - 6881:6881
      - 6881:6881/udp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.qbittorrent.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.qbittorrent.rule=Host(`${TORRENT_DOMAIN}`)'
      - 'traefik.http.routers.qbittorrent.tls=${ENABLE_SSL}'
      - 'traefik.http.routers.qbittorrent.tls.certresolver=letsencryptresolver'
      - 'traefik.docker.network=proxy_network'
      - 'traefik.http.services.qbittorrent.loadbalancer.server.port=8080'
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'docker-volume-backup.stop-during-backup=true'
    restart: unless-stopped
