---
version: '3'

volumes:
  dojo_homeassistant_data:
    external: true
  dojo_homeassistant_database:
    external: true
  dojo_influxdb_data:
    external: true
networks:
  homeassistant:
  freshrss:
  proxy_network:
    external: true
services:
  homeassistant_postgres:
    container_name: homeassistantPostgres
    image: postgres:14
    restart: always
    network_mode: host
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${HOMEASSISTANT_DB}
      POSTGRES_USER: ${HOMEASSISTANT_DB_USER}
      POSTGRES_PASSWORD: ${HOMEASSISTANT_DB_PASSWORD}
    volumes:
      - dojo_homeassistant_database:/var/lib/postgresql/data
    labels:
      - 'docker-volume-backup.stop-during-backup=true'

  homeassistant_influxdb:
    container_name: homeassistantInfluxdb
    image: influxdb:latest
    restart: always
    network_mode: host
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - INFLUXDB_DB=${HOMEASSISTANT_INFLUX_DB}
      - DOCKER_INFLUXDB_INIT_USERNAME=${HOMEASSISTANT_INFLUX_DB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${HOMEASSISTANT_INFLUX_DB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=ha-org
      - DOCKER_INFLUXDB_INIT_BUCKET=ha-bucket
    ports:
      - 8086:8086
    volumes:
      - dojo_influxdb_data:/var/lib/influxdb2
    labels:
      - 'docker-volume-backup.stop-during-backup=true'
