---
docker_stack_services:
  - name: media
    enabled: false
    ports:
      - 8096/tcp
      - 8920/tcp
      - 7539/udp
      - 1900/udp
      - 20211/tcp
    services: []
    directories:
      - path: /volumes/media/jellyfin
  - name: duckdns
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/duckdns
  - name: cloudflared
    enabled: false
    ports: []
    services: []
    directories: []
  - name: kuma
    enabled: false
    ports: []
    services: []
    directories: []
  - name: traefik
    enabled: false
    ports:
      - 8080/tcp
      - 80/tcp
      - 443/tcp
      - 1183/tcp
      - 1883/udp
      - 9001/tcp
    services: []
    directories:
      - path: /volumes/traefik/certs
      - path: /volumes/traefik/logs
  - name: watchtower
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/watchtower
  - name: portainer
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/portainer
  - name: irc
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/webirc
  - name: freshrss
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/freshrss/data
      - path: /volumes/freshrss/extensions
      - path: /volumes/freshrss/postgres
  - name: kavita
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/kavita
  - name: filebrowser
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/filebrowser
  - name: pihole
    enabled: false
    ports:
      - 53/udp
      - 53/tcp
      - 67/udp
    directories:
      - path: /volumes/pihole/data
        owner: "1000"
      - path: /volumes/pihole/dns
        owner: "1000"
    services:
      - dns
  - name: monitoring
    enabled: false
    ports: []
    directories: []
    services: []
  - name: wireguard
    enabled: false
    ports:
      - 5000/tcp
      - 51820/udp
    directories:
      - path: /volumes/wireguard/
        owner: "911"
    services: []
  - name: torrents
    enabled: false
    ports:
      - 8096/tcp
      - 8920/tcp
      - 7539/udp
      - 1900/udp
      - 8282/tcp
      - 8001/tcp
    services: []
    directories:
      - path: /volumes/torrents/rtorrent
      - path: /volumes/torrents/deluge
      - path: /volumes/torrents/sonarr
      - path: /volumes/torrents/radarr
      - path: /volumes/torrents/jacket
  - name: homeassistant
    enabled: false
    services: []
    ports: []
    directories:
      - path: /volumes/homeassistant/homeassistant
      - path: /volumes/homeassistant/influxdb
  - name: backups
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/backups
  - name: firefly
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/firefly
  - name: nextcloud
    enabled: false
    ports: []
    services: []
    directories: []
  - name: website
    enabled: false
    ports: []
    services: []
    directories:
      - path: /volumes/matomo/database
        owner: "100"
      - path: /volumes/matomo/website
        owner: "33"
      - path: /volumes/website/cms
