---
version: '3.7'

networks:
  proxy_network:
    external: true

services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.calibre.entrypoints=${CALIBRE_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.calibre.rule=Host(`${CALIBRE_DOMAIN}`)'
        - 'traefik.http.routers.calibre.tls=${CALIBRE_ENABLE_SSL}'
        - 'traefik.http.routers.calibre.tls.certresolver=letsencryptresolver'
        - 'traefik.http.services.calibre.loadbalancer.server.port=8083'
        - 'traefik.docker.network=proxy_network'
    container_name: calibre
    domainname: calibre
    security_opt:
      - seccomp:unconfined
    networks:
      - proxy_network
    ports:
      - 8083:8083
    volumes:
      - ${MEDIA_PATH}/ebooks:/books
      - ${DATA_PATH}/volumes/calibre-web:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${CALIBRE_PASSWORD}
      - CUSTOM_PORT=8082
