---
version: '3.8'

networks:
  proxy_network:
    name: proxy_network
    external: true

services:
  backup:
    image: lscr.io/linuxserver/duplicati:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.backup.entrypoints=${DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.backup.rule=Host(`${BACKUP_DOMAIN}`)'
        - 'traefik.http.routers.backup.tls=${ENABLE_SSL}'
        - 'traefik.http.routers.backup.tls.certresolver=letsencryptresolver'
        - 'traefik.http.routers.backup.service=backup'
        - 'traefik.http.services.backup.loadbalancer.server.port=8200'
        - 'traefik.docker.network=proxy_network'
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/backups/:/config
      - ${DATA_PATH}/:/source
      - ${MEDIA_PATH}/docker-backups:/backups
