---
- name: Restart openssh server
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  become: true
- name: Enable openssh server
  ansible.builtin.systemd:
    name: sshd
    state: started
  become: true
