---
version: '3.7'

networks:
  monitoring_network:
    external: true
  proxy_network:
    name: proxy_network
    external: true
services:
  emby:
    image: jellyfin/jellyfin
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.emby.entrypoints=${DEFAULT_ENDPOINT}'
      - 'traefik.http.routers.emby.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.emby.tls=${ENABLE_SSL}'
      - 'traefik.http.routers.emby.tls.certresolver=letsencryptresolver'
      - 'traefik.docker.network=proxy_network'
      - 'traefik.http.services.emby.loadbalancer.server.port=8096'
      - 'com.centurylinklabs.watchtower.enable=true'
    container_name: embyserver
    environment:
      - UID=${PUID}
      - GID=100
      - GIDLIST=100
      - JELLYFIN_PublishedServerUrl=http://${DOMAIN}
    volumes:
      - ${DATA_PATH}/volumes/media/config:/config
      - ${DATA_PATH}/volumes/media/cache:/cache
      - ${MEDIA_PATH}:/media
      - /etc/localtime:/etc/localtime:ro
    ports:
      - target: 7359
        published: 7359
        protocol: udp
        mode: host
      - target: 1900
        published: 1900
        protocol: udp
        mode: host
    networks:
      - proxy_network
