---
version: '3.7'

networks:
  monitoring_network:
    external: true
  proxy_network:
    external: true
services:
  emby:
    image: jellyfin/jellyfin
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.emby.entrypoints=${EMBY_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.emby.rule=Host(`${EMBY_DOMAIN}`)'
        - 'traefik.http.routers.emby.tls=${EMBY_ENABLE_SSL}'
        - 'traefik.http.routers.emby.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=proxy_network'
        - 'traefik.http.services.emby.loadbalancer.server.port=8096'
    container_name: embyserver
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100
      - JELLYFIN_PublishedServerUrl=http://${EMBY_DOMAIN}
    volumes:
      - ${DATA_PATH}/volumes/media/config:/config
      - ${DATA_PATH}/volumes/media/cache:/cache
      - ${MEDIA_PATH}:/media
      - /etc/localtime:/etc/localtime:ro
    ports:
      - target: 7359
        published: 7359
        protocol: udp
        mode: host
      - target: 1900
        published: 1900
        protocol: udp
        mode: host
    networks:
      - proxy_network
