---
global:
  scrape_interval: 120s
  evaluation_interval: 120s
  external_labels:
    monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files: []

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
      - targets:
          - 'localhost:9090'
          - 'cadvisor:8080'
          - 'node-exporter:9100'
          - 'nginx-exporter:9113'
  - job_name: 'openwrt-router1'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.1:9100']
  - job_name: 'speedtest'
    metrics_path: /metrics
    scrape_interval: 60m
    scrape_timeout: 60s
    static_configs:
      - targets: ['speedtest:9798']
  - job_name: 'pihole'
    static_configs:
      - targets: ['pihole_exporter:9617']
