---
version: '3.7'

networks:
  proxy_network:
    external: true

services:
  webirc:
    image: thelounge/thelounge:4.4.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.irc.entrypoints=${IRC_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.irc.rule=Host(`${IRC_DOMAIN}`)'
        - 'traefik.http.routers.irc.tls=${IRC_ENABLE_SSL}'
        - 'traefik.http.routers.irc.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=proxy_network'
        - 'com.centurylinklabs.watchtower.enable=true'
        - 'docker-volume-backup.stop-during-backup=true'
    container_name: webirc
    domainname: webirc
    restart: unless-stopped
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/webirc:/var/opt/thelounge
