---
version: "3.7"

networks:
  ipvlan2:


services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ${DATA_PATH}/volumes/wireguard/wireguard/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - SERVERURL=${VPN_SERVER_URL} #optional
      - SERVERPORT=51820 #optional
      - PEERS=${PEERS} #optional
      - PEERDNS=${PEERDNS} #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=true
