---
version: "3.7"

networks:
  proxy_network:
    name: proxy_network
    external: true

services:
  uptime:
    image: louislam/uptime-kuma:1
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime.entrypoints=${DEFAULT_ENDPOINT}
      - traefik.http.routers.uptime.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.uptime.tls=${ENABLE_SSL}
      - traefik.http.routers.uptime.service=uptime
      - traefik.http.services.uptime.loadbalancer.server.port=3001
      - traefik.http.routers.uptime.tls.certresolver=letsencryptresolver
      - traefik.docker.network=proxy_network
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/kuma/:/app/data
