---
version: '3.8'

networks:
  proxy_network:
    name: proxy_network
volumes:
  dojo_portainer_data:
    external: true
  dojo_pihole_data:
    external: true
  dojo_pihole_dns_data:
    external: true
  dojo_homeassistant_data:
    external: true
  dojo_homeassistant_database:
    external: true
  dojo_influxdb_data:
    external: true
  dojo_prometheus_data:
    external: true
  dojo_grafana_data:
    external: true
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - ${DATA_PATH}/backups:/backups
      - /var/lib/docker:/source
    ports:
      - 8200:8200
    restart: unless-stopped
  backup:
    image: offen/docker-volume-backup:v2
    restart: always
    volumes:
      - dojo_pihole_data:/backup/pihole
      - dojo_pihole_dns_data:/backup/pihole_dns
      - dojo_prometheus_data:/backup/dojo_prometheus_data
      - dojo_grafana_data:/backup/dojo_grafana_data
      - dojo_homeassistant_data:/backup/homeassistant_data
      - dojo_homeassistant_database:/backup/homeassistant_database
      - dojo_influxdb_data:/backup/influxdb_data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_PATH}/docker-backups:/archive
