---

networks:
  proxy_network:
    name: proxy_network
    external: true

services:
  kavita:
    image: jvmilazz0/kavita:nightly-0.8.0.7
    user: ${PUID}:${PGID}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.kavita.entrypoints=${DEFAULT_ENDPOINT}
      - traefik.http.routers.kavita.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.kavita.tls=${ENABLE_SSL}
      - traefik.http.services.kavita.loadbalancer.server.port=5000
      - traefik.http.routers.kavita.tls.certresolver=letsencryptresolver
      - traefik.docker.network=proxy_network
      - com.centurylinklabs.watchtower.enable=true
    container_name: kavita
    domainname: kavita
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/kavita:/kavita/config
      - ${MEDIA_PATH}/ebooks/:/books
