---
version: '3.7'

networks:
  proxy_network:
    external: true

volumes:
  filebrowser_volume:

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.filebrowser.entrypoints=${FILEBROWSER_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_DOMAIN}`)'
        - 'traefik.http.routers.filebrowser.tls=${FILEBROWSER_ENABLE_SSL}'
        - 'traefik.http.routers.filebrowser.tls.certresolver=letsencryptresolver'
        - 'traefik.http.services.filebrowser.loadbalancer.server.port=80'
        - 'traefik.docker.network=proxy_network'
    container_name: filebrowser
    domainname: filebrowser
    networks:
      - proxy_network
    volumes:
      - filebrowser_volume:/database
      - ./config/filebrowser.json:/.filebrowser.json
      - ${MEDIA_PATH}:/srv/external-data
