---
version: '3.7'

networks:
  proxy_network:
    external: true

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.freshrss.entrypoints=${FRESHRSS_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.freshrss.rule=Host(`${FRESHRSS_DOMAIN}`)'
        - 'traefik.http.routers.freshrss.tls=${FRESHRSS_ENABLE_SSL}'
        - 'traefik.http.routers.freshrss.tls.certresolver=letsencryptresolver'
        - 'traefik.http.services.freshrss.loadbalancer.server.port=80'
        - 'traefik.docker.network=proxy_network'
        - traefik.http.middlewares.freshrssM1.compress=true
        - traefik.http.middlewares.freshrssM2.headers.browserXssFilter=true
        - traefik.http.middlewares.freshrssM2.headers.forceSTSHeader=true
        - traefik.http.middlewares.freshrssM2.headers.frameDeny=true
        - traefik.http.middlewares.freshrssM2.headers.referrerPolicy=no-referrer-when-downgrade
        - traefik.http.middlewares.freshrssM2.headers.stsSeconds=31536000
        - traefik.http.routers.freshrss.middlewares=freshrssM1,freshrssM2
    container_name: freshrss
    domainname: freshrss
    networks:
      - proxy_network
    environment:
      TZ: Europe/Lisbon
      CRON_MIN: '3,33'
      PUID: ${UID}
      PGID: ${GID}
    volumes:
      - ${DATA_PATH}/volumes/freshrss/data:/var/www/FreshRSS/data
      - ${DATA_PATH}/volumes/freshrss/extensions:/var/www/FreshRSS/extensions
