---
- name: Setup Firewall
  become: true
  block:
    - name: Install cli utils
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - firewalld
        - python3-firewall
    - name: Start firewall
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
    - name: Set running firewall
      ansible.builtin.systemd:
        name: firewalld
        state: started
