---
version: '3.7'

networks:
  proxy_network:
    name: proxy_network
    external: true
  torrents_network:
    external:  true
services:
  # Web Reverse Proxy
  traefik:
    image: traefik:v2.8
    restart: always
    container_name: traefik
    domainname: ${TRAEFIK_DOMAIN}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ${DATA_PATH}/volumes/traefik/certs:/etc/certs/
      - ${DATA_PATH}/volumes/traefik/letsencrypt:/letsencrypt
      - ${DATA_PATH}/volumes/traefik/logs:/var/log
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    command:
      - '--certificatesresolvers.letsencryptresolver.acme.email=${TRAEFIK_MAIL}'
    networks:
      - proxy_network
      - torrents_network
    dns:
      - ${TRAEFIK_DNS1}
      - ${TRAEFIK_DNS2}
    extra_hosts:
      - host.docker.internal:172.17.0.1
