---
version: '3.7'

volumes:
  dojo_prometheus_data:
    external: true
  dojo_grafana_data:
    external: true

networks:
  monitoring_network:
    name: monitoring_network
    external: true
  proxy_network:
    external: true
    name: proxy_network
services:
  prometheus:
    image: prom/prometheus:latest
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.prometheus.entrypoints=${PROMETHEUS_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_DOMAIN}`)'
        - 'traefik.http.routers.prometheus.tls=${PROMETHEUS_ENABLE_SSL}'
        - 'traefik.http.routers.prometheus.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=proxy_network'
        - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
    restart: unless-stopped
    networks:
      - monitoring_network
      - proxy_network
    volumes:
      - ./prometheus/:/etc/prometheus/
      - dojo_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--query.lookback-delta=90m'
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  grafana:
    image: grafana/grafana:latest
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.grafana.entrypoints=${GRAFANA_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN}`)'
        - 'traefik.http.routers.grafana.tls=${GRAFANA_ENABLE_SSL}'
        - 'traefik.http.routers.grafana.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=proxy_network'
        - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
    restart: unless-stopped
    networks:
      - monitoring_network
      - proxy_network
    links:
      - prometheus:prometheus
    volumes:
      - dojo_grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel

  node-exporter:
    image: prom/node-exporter:latest
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    restart: unless-stopped
    networks:
      - monitoring_network
      - proxy_network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs${DATA_PATH}/data/system/containers|rootfs${DATA_PATH}/data/system/overlay2|rootfs${DATA_PATH}/data/system/netns|rootfs${DATA_PATH}/data/system/aufs)($$|/)"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    restart: unless-stopped
    privileged: true
    networks:
      - monitoring_network
      - proxy_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - ${DATA_PATH}/system/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
  speedtest:
    tty: true
    stdin_open: true
    ports:
      - 9798:9798
    image: miguelndecarvalho/speedtest-exporter
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    restart: always
    networks:
      - monitoring_network
      - proxy_network
  blackbox:
    tty: true
    stdin_open: true
    ports:
      - 9115:9115
    image: prom/blackbox-exporter
    user: "${UID}:${GID}"
    restart: always
    volumes:
      - ./blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - monitoring_network
      - proxy_network
  jaeger:
    image: jaegertracing/all-in-one:latest
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.jaeger.entrypoints=${JAEGER_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.jaeger.rule=Host(`${JAEGER_DOMAIN}`)'
        - 'traefik.http.routers.jaeger.tls=${JAEGER_ENABLE_SSL}'
        - 'traefik.http.routers.jaeger.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=proxy_network'
        - 'traefik.http.services.jaeger.loadbalancer.server.port=16686'
    ports:
      - '6831:6831'
      - '16686:16686'
    networks:
      - monitoring_network
      - proxy_network
