---
- name: Converge
  hosts: instance
  become: true
  vars_files:
    - test_data/testing.yml
  pre_tasks:
    - name: Load default vars file
      ansible.builtin.include_vars:
        dir: ../host_vars/
        files_matching: all.yml
  roles:
    - apt
    #- storage
    - resolvconf
    - firewall
    - openssh
    - fail2ban
    - cli
    - docker
    - docker_stack
