---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "geerlingguy/docker-debian12-ansible"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    vars:
      ansible_user: root

verifier:
  name: ansible
