---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: instance
  vars_files:
    - test_data/testing.yml
  tasks:
    - name: Import apt tests
      ansible.builtin.import_tasks: ./roles_test/apt_test.yml
    - name: Import common_cli tests
      ansible.builtin.import_tasks: ./roles_test/cli_test.yml
    - name: Import firewall tests
      ansible.builtin.import_tasks: ./roles_test/firewall_test.yml
    - name: Import docker tests
      ansible.builtin.import_tasks: ./roles_test/docker_test.yml
    - name: Import Openssh tests
      ansible.builtin.import_tasks: ./roles_test/openssh_test.yml
    - name: Import fail2ban tests
      ansible.builtin.import_tasks: ./roles_test/fail2ban_test.yml
