---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:version-cf3b81f0
    container_name: duckdns
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ${DATA_PATH}/volumes/duckdns:/config
    restart: always
