---
version: "3.7"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ${DATA_PATH}/volumes/duckdns:/config
    restart: always
