---

networks:
  proxy_network:
    external: true
  kaizoku_network:
services:
  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readlarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Etc/UTC
    volumes:
      - ${DATA_PATH}/volumes/torrents/readarr/data:/config 
      - ${MEDIA_PATH}:/downloads
    network_mode: service:vpn
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Etc/UTC
    volumes:
      - ${DATA_PATH}/volumes/torrents/prowlarr/data:/config
    network_mode: service:vpn
    labels:
      - com.centurylinklabs.watchtower.enable=true
  bazarr:
    image: linuxserver/bazarr:1.4.3-development
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
    labels:
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
    network_mode: service:vpn
    volumes:
      - ${DATA_PATH}/volumes/torrents/bazarr:/config
      - ${MEDIA_PATH}:/downloads

  sonarr:
    image: linuxserver/sonarr:4.0.4
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
    labels:
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
    network_mode:  service:vpn
    volumes:
      - ${DATA_PATH}/volumes/torrents/sonarr:/config
      - ${MEDIA_PATH}:/downloads

  radarr:
    image: linuxserver/radarr:5.4.6
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
    network_mode: service:vpn
    volumes:
      - ${DATA_PATH}/volumes/torrents/radarr:/config
      - ${MEDIA_PATH}:/downloads

  torrentclient:
    image: linuxserver/qbittorrent:4.6.4
    restart: always
    container_name: torrentclient
    network_mode: service:vpn
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - TZ=Etc/UTC
      - WEBUI_PORT=8383
    volumes:
      - ${DATA_PATH}/volumes/torrents/qbittorrent:/config
      - ${MEDIA_PATH}:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true

  torrentcronjob:
    build:
      context: .
      dockerfile: ./cronjob.Dockerfile
    restart: always
    network_mode: service:vpn
  
  vpn:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_PROVIDER}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
    ports:
      - 8282:8080
      - 8001:8000/tcp
      - 8010:8010
      - 54386:54386/udp
      - 9117:9117
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011
      - 7878:7878
      - 9696:9696
      - 8787:8787
    restart: unless-stopped
    labels:
      - traefik.enable=true
      
      # readarr 
      - traefik.http.routers.readarr.entrypoints=${READARR_DEFAULT_ENDPOINT}
      - traefik.http.routers.readarr.rule=Host(`${READARR_DOMAIN}`)
      - traefik.http.routers.readarr.tls=${READARR_ENABLE_SSL}
      - traefik.http.services.readarr.loadbalancer.server.port=8787
      - traefik.http.routers.readarr.service=readarr



      # prowlarr 
      - traefik.http.routers.prowlarr.entrypoints=${PROWLARR_DEFAULT_ENDPOINT}
      - traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_DOMAIN}`)
      - traefik.http.routers.prowlarr.tls=${PROWLARR_ENABLE_SSL}
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr.service=prowlarr


      # bazzar 
      - traefik.http.routers.bazarr.entrypoints=${BAZARR_DEFAULT_ENDPOINT}
      - traefik.http.routers.bazarr.rule=Host(`${BAZARR_DOMAIN}`)
      - traefik.http.routers.bazarr.tls=${BAZARR_ENABLE_SSL}
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - traefik.http.routers.bazarr.service=bazarr

      # sonarr
      - traefik.http.routers.sonarr.entrypoints=${SONARR_DEFAULT_ENDPOINT}
      - traefik.http.routers.sonarr.rule=Host(`${SONARR_DOMAIN}`)
      - traefik.http.routers.sonarr.tls=${SONARR_ENABLE_SSL}
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.service=sonarr

      # radarr
      - traefik.http.routers.radarr.entrypoints=${RADARR_DEFAULT_ENDPOINT}
      - traefik.http.routers.radarr.rule=Host(`${RADARR_DOMAIN}`)
      - traefik.http.routers.radarr.tls=${RADARR_ENABLE_SSL}
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.service=radarr

      # torrentclient
      - traefik.http.routers.torrentclient.entrypoints=${TORRENTS_DEFAULT_ENDPOINT}
      - traefik.http.routers.torrentclient.rule=Host(`${TORRENTS_DOMAIN}`)
      - traefik.http.routers.torrentclient.tls=${TORRENTS_ENABLE_SSL}
      - traefik.http.services.torrentclient.loadbalancer.server.port=8383
      - traefik.http.routers.torrentclient.service=torrentclient
      # general
      - traefik.docker.network=proxy_network
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy_network
