---

networks:
  proxy_network:
    external: true
  kaizoku_network:
services:
  bazarr:
    image: linuxserver/bazarr:1.4.3-development
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
    labels:
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
      - traefik.http.routers.bazarr.entrypoints=${BAZARR_DEFAULT_ENDPOINT}
      - traefik.http.routers.bazarr.rule=Host(`${BAZARR_DOMAIN}`)
      - traefik.http.routers.bazarr.tls=${BAZARR_ENABLE_SSL}
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - traefik.http.routers.bazarr.service=bazarr
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/torrents/bazarr:/config
      - ${MEDIA_PATH}:/downloads

  sonarr:
    image: linuxserver/sonarr:4.0.4
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
    labels:
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
      # sonarr
      - traefik.http.routers.sonarr.entrypoints=${SONARR_DEFAULT_ENDPOINT}
      - traefik.http.routers.sonarr.rule=Host(`${SONARR_DOMAIN}`)
      - traefik.http.routers.sonarr.tls=${SONARR_ENABLE_SSL}
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.service=sonarr
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/torrents/sonarr:/config
      - ${MEDIA_PATH}:/downloads
    depends_on:
      - jacket

  jacket:
    image: linuxserver/jackett:0.21.2387
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
      - traefik.http.routers.jacket.entrypoints=${JACKET_DEFAULT_ENDPOINT}
      - traefik.http.routers.jacket.rule=Host(`${JACKET_DOMAIN}`)
      - traefik.http.routers.jacket.tls=${JACKET_ENABLE_SSL}
      - traefik.http.services.jacket.loadbalancer.server.port=9117
      - traefik.http.routers.jacket.service=jacket
    networks:
      - proxy_network
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
    volumes:
      - ${DATA_PATH}/volumes/torrents/jacket:/config
      - ${MEDIA_PATH}:/downloads

  radarr:
    image: linuxserver/radarr:5.4.6
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
      - traefik.http.routers.radarr.entrypoints=${RADARR_DEFAULT_ENDPOINT}
      - traefik.http.routers.radarr.rule=Host(`${RADARR_DOMAIN}`)
      - traefik.http.routers.radarr.tls=${RADARR_ENABLE_SSL}
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.service=radarr
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/torrents/radarr:/config
      - ${MEDIA_PATH}:/downloads
    depends_on:
      - jacket

  torrentclient:
    image: linuxserver/qbittorrent:4.6.4
    restart: always
    container_name: torrentclient
    network_mode: service:vpn
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - GUID=${GUID}
      - TZ=Etc/UTC
      - WEBUI_PORT=8383
    volumes:
      - ${DATA_PATH}/volumes/torrents/qbittorrent:/config
      - ${MEDIA_PATH}:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true

  torrentcronjob:
    build:
      context: .
      dockerfile: ./cronjob.Dockerfile
    restart: always
    network_mode: service:vpn

  vpn:
    image: azinchen/nordvpn:3.7.0
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=${OPENVPN_USER}
      - PASS=${OPENVPN_PASSWORD}
      - COUNTRY=${VPN_SERVER_COUNTRIES}
      - RECREATE_VPN_CRON=5 */3 * * *
      - NETWORK=192.168.2.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
      - CHECK_CONNECTION_URL="https://www.google.com/"
      - TECHNOLOGY=${VPN_TECHNOLOGY}
    ports:
      - 8282:8080
      - 8001:8000/tcp
      - 8010:8010
      - 54386:54386/udp
      - 9117:9117
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011
    restart: unless-stopped
    labels:
      - traefik.enable=true
      # torrentclient
      - traefik.http.routers.torrentclient.entrypoints=${TORRENTS_DEFAULT_ENDPOINT}
      - traefik.http.routers.torrentclient.rule=Host(`${TORRENTS_DOMAIN}`)
      - traefik.http.routers.torrentclient.tls=${TORRENTS_ENABLE_SSL}
      - traefik.http.services.torrentclient.loadbalancer.server.port=8383
      - traefik.http.routers.torrentclient.service=torrentclient
      # general
      - traefik.docker.network=proxy_network
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy_network
