---
- name: Setup User
  block:
    - name: Add system user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: "/usr/bin/zsh"
        groups: "wheel"
        append: yes
      no_log: false
    - name: Created base folders for configs
      ansible.builtin.file:
        path: "{{ home_dir }}/{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ username }}"
        group: "{{ usergroup }}"
      with_items: "{{ users_directories }}"
