---
version: '3.7'
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - SUBDOMAINS=${DOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false
    volumes:
      - ${DATA_PATH}/volumes/duckdns:/config
    restart: always
