{
 "title": "overview-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Server Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"docker\",instance=\"node-exporter:9100\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"docker\",instance=\"node-exporter:9100\"}[2m15s])))) * 100) / count(count(node_cpu_seconds_total{job=\"docker\",instance=\"node-exporter:9100\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"docker\",instance=\"node-exporter:9100\"} - node_memory_SwapFree_bytes{job=\"docker\",instance=\"node-exporter:9100\"}) / (node_memory_SwapTotal_bytes{job=\"docker\",instance=\"node-exporter:9100\"} )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker FS Used",
   "type": "gauge",
   "description": "Used Docker FS",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_free_bytes{job=\"docker\",device=\"/dev/sdb1\"} * 100) / node_filesystem_size_bytes{job=\"docker\",device=\"/dev/sdb1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data FS Used",
   "type": "gauge",
   "description": "Used Data FS",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_free_bytes{job=\"docker\",device=\"/dev/sda1\"} * 100) / node_filesystem_size_bytes{job=\"docker\",device=\"/dev/sda1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System FS Used",
   "type": "gauge",
   "description": "Used System FS",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_free_bytes{job=\"docker\",device=\"/dev/root\"} * 100) / node_filesystem_size_bytes{job=\"docker\",device=\"/dev/root\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"docker\"} * 100) / node_memory_MemTotal_bytes{job=\"docker\" })",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"docker\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System FS Total",
   "type": "stat",
   "description": "Total System FS",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"docker\",device=\"/dev/root\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"docker\" }",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DockerFSTotal",
   "type": "stat",
   "description": "Total DockerFS",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/sdb1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"$job\",instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "DataFS Total",
   "type": "stat",
   "description": "Total DataFS",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"docker\",device=\"/dev/sda1\", fstype=\"ext4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Local Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"speedtest:9798\"}*10^-6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"speedtest:9798\"}*10^-6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"speedtest:9798\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{hostname=~'pihole'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_unique_domains{hostname=\"pihole\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{hostname=~'pihole'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"speedtest:9798\"}*10^-6",
     "legendFormat": "Upload Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Download Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"speedtest:9798\"}*10^-6",
     "legendFormat": "Download Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Most blocked domains",
   "type": "table",
   "description": "Most blocked domains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "topk(15, sum(pihole_top_ads) by (domain))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Blocked Devices",
   "type": "table",
   "description": "Top Blocked Devices",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "topk(15, sum(pihole_top_sources{job=\"pihole\"}) by (source))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Status code over 60min for WebSecure Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint =~\"websecure\"}[60m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status code over 60min for Web Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint =~\"web\"}[60m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{}) by (service) / sum(traefik_service_request_duration_seconds_count{}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests By Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[60m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total[60m])) by (entrypoint) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}