---
version: "3.7"

networks:
  proxy_network:
    name: proxy_network
    external: true
  freshrss:
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:1.23.1
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.entrypoints=${DEFAULT_ENDPOINT}
      - traefik.http.routers.freshrss.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.freshrss.tls=${ENABLE_SSL}
      - traefik.http.services.freshrss.loadbalancer.server.port=80
      - traefik.http.routers.freshrss.tls.certresolver=letsencryptresolver
      - traefik.docker.network=proxy_network
      - traefik.http.middlewares.freshrssM1.compress=true
      - traefik.http.middlewares.freshrssM2.headers.browserXssFilter=true
      - traefik.http.middlewares.freshrssM2.headers.forceSTSHeader=true
      - traefik.http.middlewares.freshrssM2.headers.frameDeny=true
      - traefik.http.middlewares.freshrssM2.headers.referrerPolicy=no-referrer-when-downgrade
      - traefik.http.middlewares.freshrssM2.headers.stsSeconds=31536000
      - traefik.http.routers.freshrss.middlewares=freshrssM1,freshrssM2
      - com.centurylinklabs.watchtower.enable=true
    container_name: freshrss
    domainname: freshrss
    networks:
      - proxy_network
      - freshrss
    environment:
      TZ: Europe/Lisbon
      PUID: ${PUID}
      PGID: ${PGID}
      CRON_MIN: ${CRON_MIN}
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}/volumes/freshrss/data:/config
    links:
      - freshrss_db

  freshrss_db:
    image: postgres:16
    restart: always
    container_name: freshrss-db
    networks:
      - freshrss
    logging:
      options:
        max-size: 10m
    volumes:
      - ${DATA_PATH}/volumes/freshrss/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${FRESHRSS_DB}
      POSTGRES_USER: ${FRESHRSS_DB_USER}
      POSTGRES_PASSWORD: ${FRESHRSS_DB_PASSWORD}
    command:
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=32MB

  freshrss_postgres_backups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
      - ${DATA_PATH}/docker-backups/databases:/backups
    links:
      - freshrss_db
    networks:
      - freshrss
    environment:
      - POSTGRES_HOST=freshrss_db
      - POSTGRES_DB=${FRESHRSS_DB}
      - POSTGRES_USER=${FRESHRSS_DB_USER}
      - POSTGRES_PASSWORD=${FRESHRSS_DB_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
