---
metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics
    buckets:
      - !!float "0.1"
      - !!float "0.3"
      - 1.2
      - 5.0

entryPoints:
  metrics:
    address: :8082
  web:
    address: :80
  websecure:
    address: :443
  mqtt:
    address: :1883
  mqtt_websocket:
    address: :9001

certificatesResolvers:
  letsencryptresolver:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
      storage: /letsencrypt/acme.json

accesslog:
  filePath: /var/log/acccess.log
  filters:
    statusCodes: 400-499

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: proxy_network
    exposedbydefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
