---
version: "3.7"

networks:
  proxy_network:
    name: proxy_network
    external: true

services:
  backup:
    image: lscr.io/linuxserver/duplicati:latest
    env_file:
      - .env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.backup.entrypoints=${DEFAULT_ENDPOINT}
      - traefik.http.routers.backup.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.backup.tls=${ENABLE_SSL}
      - traefik.http.routers.backup.service=backup
      - traefik.http.routers.backup.tls.certresolver=letsencryptresolver
      - traefik.http.services.backup.loadbalancer.server.port=8200
      - traefik.docker.network=proxy_network
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/backups/:/config
      - ${DATA_PATH}/docker-backups/:/source
      - ${MEDIA_PATH}/docker-backups:/backups
