---
- name: Setup Storage
  become: true
  block:
    - name: Configure disk mounts in /etc/fstab
      ansible.posix.mount:
        path: "{{ item.dest }}"
        src: "{{ item.src }}"
        fstype: "{{ item.filetype }}"
        opts: "{{ item.opts }}"
        state: mounted
      with_items: "{{ storage_configs }}"

    - name: Change mount directories ownership
      ansible.builtin.file:
        path: "{{ item.dest }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0744"
      with_items: "{{ storage_configs }}"
