---
version: "3.7"

networks:
  homeassistant_network:
  monitoring_network:
    name: monitoring_network
    external: true
  proxy_network:
    name: proxy_network
    external: true
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2024.3
    networks:
      - proxy_network
      - homeassistant_network
    ports:
      - 8123:8123
      - 5683:5683
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_network
      - traefik.http.routers.homeassistant.entrypoints=${DEFAULT_ENDPOINT}
      - traefik.http.routers.homeassistant.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homeassistant.tls=${ENABLE_SSL}
      - traefik.http.routers.homeassistant.tls.certresolver=letsencryptresolver
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ${DATA_PATH}/volumes/homeassistant/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    dns:
      - 192.168.2.4
      - 192.168.2.1
      - 1.1.1.1
    depends_on:
      - homeassistant_postgres
      - homeassistant_influxdb

  homeassistant_postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${HOMEASSISTANT_DB}
      POSTGRES_USER: ${HOMEASSISTANT_DB_USER}
      POSTGRES_PASSWORD: ${HOMEASSISTANT_DB_PASSWORD}
    volumes:
      - ${DATA_PATH}/volumes/homeassistant/postgres:/var/lib/postgresql/data
    networks:
      - homeassistant_network

  homeassistant_postgres_backups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
      - ${DATA_PATH}/docker-backups/databases:/backups
    links:
      - homeassistant_postgres
    networks:
      - homeassistant_network
    environment:
      - POSTGRES_HOST=homeassistant_postgres
      - POSTGRES_DB=${HOMEASSISTANT_DB}
      - POSTGRES_USER=${HOMEASSISTANT_DB_USER}
      - POSTGRES_PASSWORD=${HOMEASSISTANT_DB_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

  homeassistant_influxdb:
    image: influxdb:latest
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - INFLUXDB_DB=${HOMEASSISTANT_INFLUX_DB}
      - DOCKER_INFLUXDB_INIT_USERNAME=${HOMEASSISTANT_INFLUX_DB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${HOMEASSISTANT_INFLUX_DB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=ha-org
      - DOCKER_INFLUXDB_INIT_BUCKET=ha-bucket
    volumes:
      - ${DATA_PATH}/volumes/homeassistant/influxdb:/var/lib/influxdb2
    networks:
      - homeassistant_network
      - monitoring_network

  homeassistant_mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${DATA_PATH}/volumes/homeassistant/mosquitto:/mosquitto
    networks:
      - homeassistant_network
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant_mosquitto.rule=Host(`${MQTT_DOMAIN}`)"
      - "traefik.http.routers.homeassistant_mosquitto.entrypoints=${DEFAULT_ENDPOINT}"
      - "traefik.http.routers.homeassistant_mosquitto.tls.certresolver=letsencryptresolver"
      - "traefik.tcp.routers.homeassistant_mosquitto.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.homeassistant_mosquitto.tls.certresolver=letsencryptresolver"
      - "traefik.tcp.services.homeassistant_mosquitto.loadbalancer.server.port=1883"
      - "traefik.tcp.routers.homeassistant_mosquitto.entrypoints=mqtt"
      - "traefik.http.services.homeassistant_mosquitto.loadbalancer.server.port=9001"
    expose:
      - 1883
      - 9001

  databases_backups:
    image: huacnlee/gobackup
    volumes:
      - ${DATA_PATH}/volumes/homeassistant/go-backups:/etc/gobackup
      - ${DATA_PATH}/docker-backups/homeassistant/:/backups
    restart: always
    ports:
      - 2703:2703
    networks:
      - homeassistant_network
      - proxy_network
    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy_network
        - traefik.http.routers.homeassistant_backups.entrypoints=${DEFAULT_ENDPOINT}
        - traefik.http.routers.homeassistant_backups.rule=Host(`${HA_BACKUP_DOMAIN}`)
        - traefik.http.routers.homeassistant_backups.tls=${ENABLE_SSL}
        - traefik.http.routers.homeassistant_backups.tls.certresolver=letsencryptresolver
        - traefik.http.services.homeassistant_backups.loadbalancer.server.port=2703
        - com.centurylinklabs.watchtower.enable=true
