---
- name: "Common cli test - check package status"
  ansible.builtin.package:
    name: "docker"
    state: "present"
  check_mode: yes
  register: pkg_status

- name: Install docker pages
  become: true
  block:
  - name: Download scripts
    get_url:
      url: "https://get.docker.com/"
      dest: "/tmp/get-docker.sh"
      mode: "0776"
  - name: Install docker
    command: "/tmp/get-docker.sh"
    environment:
      CHANNEL: stable

  - name: Install containers packages
    ansible.builtin.package:
      name: '{{ item }}'
      state: present
      update_cache: true
    with_items:
      - docker-compose
  - name: 'Just force systemd to reread configs'
    ansible.builtin.systemd:
      daemon_reload: true
  - name: 'Start docker'
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: true
  - name: 'Add user to docker group'
    ansible.builtin.user:
      name: '{{ username }}'
      groups: docker
      append: true
  - name: Enable docker swarm mode
    docker_swarm:
      state: present
      advertise_addr: "{{ docker_swarm_advertise_addr }}"
    register: output
    when: enable_docker_swarm_mode|bool == true
  when: not pkg_status.changed
