---
- name: Common cli test - check package status
  ansible.builtin.package:
    name: docker-ce
    state: present
  check_mode: true
  ignore_errors: true
  changed_when: false
  register: pkg_status

- name: Install docker pages
  become: true
  when: pkg_status is not succeeded
  block:
    - name: Download scripts
      ansible.builtin.get_url:
        url: https://get.docker.com/
        dest: /tmp/get-docker.sh
        mode: "0776"
    - name: Install docker
      ansible.builtin.command: /tmp/get-docker.sh
      environment:
        CHANNEL: stable
      tags:
        - skip_ansible_lint

    - name: Install containers packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - docker-compose
    - name: Just force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Copy docker custom configs
      ansible.builtin.template:
        src: "{{ item.origin_name }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      with_items:
        - origin_name: daemon.json.j2
          dest: /etc/docker/daemon.json

    - name: Start docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

- name: Get group membership
  getent:
    database: docker
  check_mode: true
  ignore_errors: true
  changed_when: false
  register: group_info

- name: Check if user is in group
  set_fact:
    user_in_group: "{{ group_info.entries | selectattr('users', 'search', username) | list }}"


- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  when: not in user_in_group
