---
version: "3.7"

networks:
  proxy_network:
    name: proxy_network
    external: true

services:
  webirc:
    image: thelounge/thelounge:4.4.0
    user: ${PUID}:${PGID}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.irc.entrypoints=${DEFAULT_ENDPOINT}
      - traefik.http.routers.irc.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.irc.tls=${ENABLE_SSL}
      - traefik.http.services.irc.loadbalancer.server.port=9000
      - traefik.http.routers.irc.tls.certresolver=letsencryptresolver
      - traefik.docker.network=proxy_network
      - com.centurylinklabs.watchtower.enable=true
    container_name: webirc
    domainname: webirc
    networks:
      - proxy_network
    volumes:
      - ${DATA_PATH}/volumes/webirc:/var/opt/thelounge
