
---
version: '3.7'

networks:
  proxy_network:
    external: true
  torrents_network:
    external:  true

services:
  wireguard:
    image: linuxserver/wireguard:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=false
    hostname: wireguard
    networks:
      - torrents_network
      - proxy_network
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Etc/UTC
      - SERVERPORT=51820
      - INTERNAL_SUBNET=172.16.204.0/24
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - /lib/modules:/lib/modules
      - ${DATA_PATH}/volumes/torrents/wireguard/wg0.conf:/config/wg0.conf
      - ./dante-server/danted.conf:/etc/danted.conf
      - ./dante-server/install.sh:/custom-cont-init.d/install.sh:ro
      - ./dante-server/run.sh:/custom-services.d/run.sh:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
  sonarr:
    image: linuxserver/sonarr:arm64v8-3.0.10
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.sonarr.entrypoints=${SONARR_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.sonarr.rule=Host(`${SONARR_DOMAIN}`)'
        - 'traefik.http.routers.sonarr.tls=${SONARR_ENABLE_SSL}'
        - 'traefik.http.routers.sonarr.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=proxy_network'
        - 'traefik.http.services.sonarr.loadbalancer.server.port=8989'
    hostname: sonarr
    networks:
      - proxy_network
      - torrents_network
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DATA_PATH}/volumes/torrents/sonarr:/config
      - ${MEDIA_PATH}:/downloads
    depends_on:
      - gluetun
      - jacket

  jacket:
    image: linuxserver/jackett:arm64v8-0.21.568
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.jacket.entrypoints=${JACKET_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.jacket.rule=Host(`${JACKET_DOMAIN}`)'
        - 'traefik.http.routers.jacket.tls=${JACKET_ENABLE_SSL}'
        - 'traefik.http.routers.jacket.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=proxy_network'
        - 'traefik.http.services.jacket.loadbalancer.server.port=9117'
    hostname: jacket
    networks:
      - proxy_network
      - torrents_network
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DATA_PATH}/volumes/torrents/jacket:/config
      - ${MEDIA_PATH}:/downloads
    depends_on:
      - gluetun

  radarr:
    image: linuxserver/radarr:arm64v8-4.6.4
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.radarr.entrypoints=${RADARR_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.radarr.rule=Host(`${RADARR_DOMAIN}`)'
        - 'traefik.http.routers.radarr.tls=${RADARR_ENABLE_SSL}'
        - 'traefik.http.routers.radarr.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=proxy_network'
        - 'traefik.http.services.radarr.loadbalancer.server.port=7878'
    networks:
      - proxy_network
      - torrents_network
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DATA_PATH}/volumes/torrents/radarr:/config
      - ${MEDIA_PATH}:/downloads
    depends_on:
      - gluetun
      - jacket

  torrentclient:
    image: lscr.io/linuxserver/qbittorrent:latest
    user: "${UID}:${GID}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.torrentclient.entrypoints=${TORRENTS_DEFAULT_ENDPOINT}'
        - 'traefik.http.routers.torrentclient.rule=Host(`${TORRENTS_DOMAIN}`)'
        - 'traefik.http.routers.torrentclient.tls=${TORRENTS_ENABLE_SSL}'
        - 'traefik.http.routers.torrentclient.tls.certresolver=letsencryptresolver'
        - 'traefik.docker.network=torrents_network'
        - 'traefik.http.services.torrentclient.loadbalancer.server.port=8080'
    container_name: torrentclient
    networks:
      - torrents_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DATA_PATH}/volumes/torrents/qbittorrent:/config/qBittorrent
      - ${MEDIA_PATH}:/downloads
    depends_on:
      - wireguard
