---

storage_configs:
  - src: "PARTUUID=eb6d65c3-3b33-409b-87f5-5cf09f81b964"
    dest: /home/rubemlrm/external-data
    filetype: ext4
    opts: rw,async

docker_stack_services_custom:
  - name: media
    enabled: true
  - name: cloudflared
    enabled: true
  - name: traefik
    enabled: true
  - name: watchtower
    enabled: true
  - name: kavita
    enabled: true
  - name: pihole
    enabled: true
  - name: monitoring
    enabled: true
  - name: torrents
    enabled: true
  - name: homeassistant
    enabled: true
  - name: backups
    enabled: true
  - name: website
    enabled: true
  - name: github_runners
    enabled: true
  - name: nextcloud
    enabled: true
  - name: filebrowser
    enabled: true
