---
docker_stack_services:
  - name: media
    ports:
      - 8096/tcp
      - 8920/tcp
      - 7539/udp
      - 1900/udp
      - 20211/tcp
    services: []
    directories:
      - path: /volumes/media/jellyfin
  - name: duckdns
    ports: []
    services: []
    directories:
      - path: /volumes/duckdns
  - name: cloudflared
    ports: []
    services: []
    directories: []
  - name: kuma
    ports: []
    services: []
    directories: []
  - name: traefik
    ports:
      - 8080/tcp
      - 80/tcp
      - 443/tcp
      - 1183/tcp
      - 1883/udp
      - 9001/tcp
    services: []
    directories:
      - path: /volumes/traefik/certs
      - path: /volumes/traefik/logs
  - name: watchtower
    ports: []
    services: []
    directories:
      - path: /volumes/watchtower
  - name: portainer
    ports: []
    services: []
    directories:
      - path: /volumes/portainer
  #- name: irc
  #  ports: []
  #  services: []
  #  directories:
  #    - path: /volumes/webirc
  #- name: freshrss
  #  ports: []
  #  services: []
  #  directories:
  #    - path: /volumes/freshrss/data
  #    - path: /volumes/freshrss/extensions
  #    - path: /volumes/freshrss/postgres
  - name: kavita
    ports: []
    services: []
    directories:
      - path: /volumes/kavita
  - name: filebrowser
    ports: []
    services: []
    directories:
      - path: /volumes/filebrowser
  - name: pihole
    ports:
      - 53/udp
      - 53/tcp
      - 67/udp
    directories:
      - path: /volumes/pihole/data
        owner: "1000"
      - path: /volumes/pihole/dns
        owner: "1000"
    services:
      - dns
  - name: monitoring
    ports: []
    directories: []
    services: []
  - name: wireguard
    ports:
      - 5000/tcp
      - 51820/udp
    directories:
      - path: /volumes/wireguard/
        owner: "911"
    services: []
  - name: torrents
    ports:
      - 8096/tcp
      - 8920/tcp
      - 7539/udp
      - 1900/udp
      - 8282/tcp
      - 8001/tcp
    services: []
    directories:
      - path: /volumes/torrents/rtorrent
      - path: /volumes/torrents/deluge
      - path: /volumes/torrents/sonarr
      - path: /volumes/torrents/radarr
      - path: /volumes/torrents/jacket
  - name: homeassistant
    services: []
    ports: []
    directories:
      - path: /volumes/homeassistant/homeassistant
      - path: /volumes/homeassistant/influxdb
  - name: backups
    ports: []
    services: []
    directories:
      - path: /volumes/backups
  - name: firefly
    ports: []
    services: []
    directories:
      - path: /volumes/firefly
  - name: nextcloud
    ports: []
    services: []
    directories: []
  - name: website
    ports: []
    services: []
    directories:
      - path: /volumes/matomo/database
        owner: "100"
      - path: /volumes/matomo/website
        owner: "33"
      - path: /volumes/website/cms
