---

storage_configs:
  - src: "PARTUUID=eb6d65c3-3b33-409b-87f5-5cf09f81b964"
    dest: /home/rubemlrm/external-data
    filetype: ext4
    opts: rw,async

docker_stack_services_custom:
  - name: media
    enabled: true
  - name: duckdns
    enabled: true
  - name: cloudflared
    enabled: true
  - name: kuma
    enabled: true
  - name: traefik
    enabled: true
  - name: watchtower
    enabled: true
  - name: portainer
    enabled: true
  - name: irc
    enabled: false
  - name: freshrss
    enabled: false
  - name: kavita
    enabled: true
  - name: filebrowser
    enabled: false
  - name: pihole
    enabled: true
  - name: monitoring
    enabled: true
  - name: wireguard
    enabled: true
  - name: torrents
    enabled: true
  - name: homeassistant
    enabled: true
  - name: backups
    enabled: true
  - name: firefly
    enabled: false
  - name: nextcloud
    enabled: false
  - name: website
    enabled: true
