metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

entryPoints:
  metrics:
    address: ":8082"
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencryptresolver:
    acme:
      httpChallenge:
        entrypoint: web
      storage: "/letsencrypt/acme.json"


accesslog:
  filePath: "/var/log/acccess.log"
  filters:
    statusCodes: "400-499"

api:
  dashboard: true
  insecure: true

tracing:
  jaeger:
    samplingServerUrl:  "http://jaeger:5778/sampling"
    localAgentHostPort: "jaeger:6831"

ping: {}

experimental:
  plugins:
    fail2ban:
      modulename: "github.com/tomMoulard/fail2ban"
      version: "v0.6.6"

providers:
  docker:
    network: proxy_network
    exposedbydefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
