---
# Loads default set of integrations. Do not remove.
default_config:
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies:
    - 172.24.0.0/24
    - 172.18.0.0/24
    - 172.19.0.0/24
    - 127.0.0.1
    - 10.0.15.21
    - ::1
    - fe80::/64
    - fe00::/65
    - fd01::/64
    - 10.0.15.0/24
    - 10.0.4.0/24
    - 10.11.0.0/24

influxdb:
  api_version: 2
  ssl: false
  host: homeassistant_influxdb
  port: 8086
  database: home
  organization: ha-org
  bucket: ha-bucket
  max_retries: 3
  token: !secret influxdb_token

recorder:
  db_url: !secret postgres_url
  auto_purge: false

device_tracker:
  - platform: luci
    host: 192.168.2.1
    username: !secret router_user
    password: !secret router_password

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  external_url: !secret external_url

python_script:
