# This is a basic workflow to help you get started with Actions

name: LINTERS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint_env:
    runs-on: ubuntu-latest
    name: Lint Env File
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Super-Linter
        uses: docker://ghcr.io/github/super-linter:v4.7.0
        env:
           VALIDATE_ALL_CODEBASE: true
           VALIDATE_ENV: true
  lint_yaml:
    runs-on: ubuntu-latest
    name: Lint Docker Base
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Super-Linter
        uses: docker://ghcr.io/github/super-linter:v4.7.0
        env:
           VALIDATE_ALL_CODEBASE: true
           VALIDATE_YAML: true
