---
name: LINTERS

on:
  pull_request:
    branches:
      - main

jobs:
  lint_env:
    runs-on: ubuntu-latest
    name: Lint Env File
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Super-Linter
        uses: docker://ghcr.io/github/super-linter:v4.7.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_ENV: true
  lint_yaml:
    runs-on: ubuntu-latest
    name: Lint Docker Base
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Super-Linter
        uses: docker://ghcr.io/github/super-linter:v4.7.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
