version: '3.7'


networks:
  proxy_network:
    external: true

services:
  couchdb:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        # The Traefik Network
        - "traefik.docker.network=proxy_network"
        - "traefik.http.routers.obsidian-livesync.rule=Host(`${OBSIDIAN_DOMAIN}`)"
        - "traefik.http.routers.obsidian-livesync.entrypoints=${OBSIDIAN_DEFAULT_ENDPOINT}"
        - "traefik.http.routers.obsidian-livesync.service=obsidian-livesync"
        - "traefik.http.services.obsidian-livesync.loadbalancer.server.port=5984"
        - "traefik.http.routers.obsidian-livesync.tls=${OBSIDIAN_ENABLE_SSL}"
        - "traefik.http.routers.obsidian-livesync.tls.certresolver=letsencrypt"
        - "traefik.http.routers.obsidian-livesync.middlewares=obsidiancors"
        - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE"
        - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer"
        - "traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost"
        - "traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage=3600"
        - "traefik.http.middlewares.obsidiancors.headers.addvaryheader=true"
        - "traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials=true"

    image: couchdb:latest
    container_name: obsidian-livesync
    user: "${UID}:${GID}"
    environment:
      - COUCHDB_USER=${OBSIDIAN_USER}
      - COUCHDB_PASSWORD=${OBSIDIAN_PASSWORD}
    volumes:
      - ${DATA_PATH}/volumes/obsidian-sync:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: unless-stopped
    networks:
      - proxy_network
